***Hello***

In [1]:
import numpy as np

In [2]:
myarr=np.array([3,6,37,7],np.int64)

In [3]:
myarr[0]

3

In [4]:
np.array({22,54})

array({54, 22}, dtype=object)

In [5]:
zeroes=np.zeros((2,2))

In [6]:
zeroes

array([[0., 0.],
       [0., 0.]])

In [7]:
zeroes.dtype

dtype('float64')

In [8]:
zeroes.shape

(2, 2)

In [9]:
rng=np.arange(15)

In [10]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
lspace=np.linspace(1,4,4)

In [12]:
lspace

array([1., 2., 3., 4.])

In [13]:
empty=np.empty((1,6))

In [14]:
empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.42413555e-306, 1.78019082e-306]])

In [15]:
emptylike=np.empty_like(lspace)

In [16]:
emptylike

array([1., 2., 3., 4.])

In [17]:
ide=np.identity(3)

In [18]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
arr=np.arange(99)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [21]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [23]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
x=[[1,2,3,],[4,5,6],[7,8,9]]

In [25]:
arr=np.array(x)

In [26]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr.sum(axis=0)

array([12, 15, 18])

In [28]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [29]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [30]:
arr.ndim

2

In [32]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [33]:
arr.nbytes

36

In [34]:
arr.argmax()

8

In [35]:
arr.argmin()

0

In [36]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [37]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [38]:
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [42]:
arr.sum()

45

In [43]:
arr.min()

1

In [44]:
arr.max()

9

In [46]:
type(np.where(arr>3))

tuple

In [47]:
np.count_nonzero(arr)

9

In [48]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [49]:
import sys

In [50]:
py_ar=[0,4,55,2]

In [51]:
np_ar=np.array(py_ar)

In [52]:
sys.getsizeof(1)*len(py_ar)

112

In [53]:
np_ar.itemsize*np_ar.size

16